name: flutter_sixvalley_ecommerce
description: A new Flutter setup application for starting a project.

publish_to: 'none'
version: 2.0.9+9
environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  provider: ^6.0.3
  connectivity_plus: ^6.1.2
  dio: ^5.3.4
  http: ^1.1.1
  shared_preferences: ^2.0.5
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.3
  image_picker: ^1.0.7
  webview_flutter: ^4.4.4
  flutter_widget_from_html_core: ^0.15.2
  share_plus: ^10.1.4
  photo_view: ^0.15.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.2
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.9
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  flutter_typeahead: ^5.2.0
  marquee: ^2.2.1
  flutter_rating_bar: ^4.0.0
  flutter_widget_from_html: ^0.15.3
  fluttertoast: ^8.0.9
  permission_handler: ^11.1.0
  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.1.5
  path: ^1.8.3
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  flutter_slidable: ^3.0.0
  percent_indicator: ^4.2.3
  just_the_tooltip: ^0.0.12
  substring_highlight: ^1.0.33
  card_swiper: ^3.0.1
  just_audio: ^0.9.36
  file_picker: ^8.0.0+1
  carousel_slider: ^5.0.0
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.10.1
  dropdown_button2: ^2.3.9
  gradient_borders: ^1.0.0
  flutter_spinkit: ^5.2.1
  open_file_plus: ^3.4.1
  flutter_pdfview: ^1.2.7
  readmore: ^3.0.0
  open_file_manager: ^1.0.2
  flutter_launcher_icons: ^0.14.3
  cloud_firestore: ^5.6.1
  flutter_html: ^3.0.0-beta.2
  smooth_page_indicator: ^1.2.0+3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mazrrattilogo.png"
  min_sdk_android: 21 
  


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: SF-Pro-Rounded-Regular
      fonts:
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/SF-Pro-Rounded-Regular.ttf
          weight: 600
    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/Din Next Lt Arabic Light.otf
          weight: 300
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/DINNextLTArabic-Black.ttf
          weight: 900
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/DINNextLTArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/DINNextLTArabic-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/DINNextLTArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/DINNextLTArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/Din_Next_Lt_Arabic_Family/DINNextLTArabic-UltraLight.ttf
          weight: 200
